### ISSUE TITLE
Does not work with Falcon 1.0

### ISSUE THREAD

**Issue by fvox13** [talons/talons#40]
Falcon 1.0 introduced the requirement for "challenges" when returning 401 Status Codes.
http://falcon.readthedocs.io/en/stable/changes/1.0.0.html?highlight=challenges#breaking-changes

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/falcon/api.py", line 172, in __call__
    self._call_req_mw(middleware_stack, req, resp)
  File "/usr/local/lib/python3.4/dist-packages/falcon/api.py", line 550, in _call_req_mw
    process_request(req, resp)
  File "./middleware/auth.py", line 156, in process_request
    self.mw(request, response, None)
  File "/usr/local/lib/python3.4/dist-packages/talons/auth/middleware.py", line 105, in __call__
    self.raise_401_no_identity()
  File "/usr/local/lib/python3.4/dist-packages/talons/auth/middleware.py", line 83, in raise_401_no_identity
    'No identity information found.')
TypeError: __init__() missing 1 required positional argument: 'challenges'
```

As near as I can tell, this is the only change that would be required to support Falcon 1.0.

There was a retracted pull request here that looks like it would have fixed this:
https://github.com/talons/talons/pull/38/files

Can this be merged, or should I try my hand at fixing it a different way and submit a fresh pull request?

**Comment by jaypipes** [comment]
Hi!

Talons does not work with Falcon greater than 0.4. The Falcon community changed the interfaces for hooks and middleware interfaces dramatically between 0.2 and 0.4 and I haven't been able to devote any time to updating Talons to work with multiple versions of Falcon.

I would certainly consider any pull requests that you send over that allow Talons to work with post 0.4 versions of Falcon. My only request is that you add some tests in your patch that validate Falcon 0.4 and before don't break horribly :)

Thank you!
-jay

**Comment by jaypipes** [comment]
Sorry, when I wrote Falcon 0.4 above, I meant 0.3!
